### PR TITLE
Prefix call handler name with mocked module

### PR DESCRIPTION
**Pull request by stwind**
When mocking more than one modules, the call handers for them have a same gen_server name, which making second ones failed to start.

So prefix the call handler name with the mocked module to allow mocking multiple modules.

### CODE REVIEW

**Comment by samuelrivas** [comment]
Thanks for your contribution! I will try to merge today when I am back home.

I would like to have a simple test that triggers this bug, Could you create a simple eunit test in a new component/moka_server_tests suite?

It is rather unfortunate that there are no single tests for more than one concurrent moka (and apparently I have never created more than one moka in anywere...), I probably need to add some proper tests for that.

**Comment by stwind** [comment]
Sorry for not having a test case for this change, I'll write one later.

**Comment by samuelrivas** [comment]
Superb, thanks a lot

**Comment by samuelrivas** [comment]
I will merge your changes to `develop` right now. If you don't have time to create a test I can write one and then merge to `master`

**Comment by samuelrivas** [comment]
Merged into 1.0.1, and added a simple test for it. I will create an issue to think about better tests for concurrent mokas later.

Thanks for fixing this embarrassing bug :)

**Pull request merged**
