### PR TITLE
FUNCT prepend moka module to call handler name

### PR DESCRIPTION
**Pull request by stwind**
hi @samuelrivas , thank you for the inspiring work of moka.

I am currently using moka in one of my projects, and some use cases make me think that it may be better to name the call handler gen_server as a combination of the moka, mocked module and mock count.

Here is one my my use case:
I have a `foo.erl` and `bar.erl`, in both modules, they call `baz:something()`. And I want `baz:something()` behaves differently in `foo.erl` and `bar.erl`. So I do:

``` erlang
Moka1 = moka:start(foo),
Moka2 = moka:start(bar),
moka:replace(Moka1, baz, something, fun() -> hoge end),
moka:replace(Moka2, baz, something, fun() -> piyo end),
```

This leads to same results of #16, since the call handler is name only after `baz`. So making it something like `foo_baz` and `bar_baz` should be the solution.

### CODE REVIEW

**Comment by samuelrivas** [comment]
I am happy to know moka is useful for you :) Sorry for the buggy call handler names, I was not happy with the count solution, but since it never gave me problems I haven't prioritised thinking about a better solution.

I haven't looked carefully into it now, but after adding the moka name to the handler, is it not enough with just the counter? There cannot be two mokas with the same name, and then each moka would generate a safe space of names on its own.

An alternative might be a combination of "moked module", "called module", "called function" and arity, that should be enough to get rid of the counter

In any case I will merge this when I am back home so you can keep on working, and try to take a closer look to the call handlers later.

**Comment by stwind** [comment]
yeah, a combination of "moked module", "called module", "called function" and arity should be better, and history can be more specific too :)

**Comment by samuelrivas** [comment]
Do you mean the history server? Because that is created per moka, not per substitution. Or do you have another idea?

BTW, is your project opensourced so I can take a look to your moka usages for inspiration?

**Comment by samuelrivas** [comment]
Thanks a lot for your contribution!

**Comment by stwind** [comment]
It is not an opensource project, but here is my typical setup for a common test suite. https://gist.github.com/stwind/6109054

It also reminds me that I have to use a little hack on the behavior function to get around the `crashfy:untuple/1`, I'll create another ticket for it :)

**Pull request merged**
